services:
    orangegate.export.serializer:
        class: Symbio\OrangeGate\ExportBundle\Service\Serializer
        arguments: [ null, @doctrine.orm.entity_manager]

    orangegate.export.deserializer:
        class: Symbio\OrangeGate\ExportBundle\Service\Deserializer
        arguments: [ null, @doctrine.orm.entity_manager]

    orangegate.export.fileexporter:
        class: Symbio\OrangeGate\ExportBundle\Service\MediaFileExporter
        arguments: [ @sonata.media.twig.extension, @doctrine.orm.entity_manager, %kernel.root_dir%]

    orangegate.export.zipexporter:
        class: Symbio\OrangeGate\ExportBundle\Service\ZipExporter
        arguments: [@orangegate.export.serializer, @orangegate.export.fileexporter]
