Symbio\OrangeGate\PageBundle\Entity\LanguageVersion:
    properties:
        name:
            type: string
        enabled:
            type: boolean
        host:
            type: string
        locale:
            type: string
        isDefault:
            type: boolean
        site:
            exlude: true
            type: Symbio\OrangeGate\PageBundle\Entity\Site
        id:
            exclude: true
            type: integer
        created_at:
            type: DateTime
            exclude: true
        updated_at:
            type: DateTime
            exclude: true
